tagFormat: ${version}
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: build
          scope: deps
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: build
            scope: deps
            secrtion: deps
          - type: feat
            section: Features
          - type: feature
            section: Features
          - type: fix
            section: Bug Fixes
          - type: perf
            section: Performance Improvements
          - type: revert
            section: Reverts
          - type: docs
            section: Documentation
            hidden: 'true'
          - type: style
            section: Styles
            hidden: 'true'
          - type: chore
            section: Miscellaneous Chores
            hidden: 'true'
          - type: refactor
            section: Code Refactoring
            hidden: 'true'
          - type: test
            section: Tests
            hidden: 'true'
          - type: build
            section: Build System
            hidden: 'true'
          - type: ci
            section: Continuous Integration
            hidden: 'true'
  - - "@semantic-release/exec"
    - verifyReleaseCmd: 'if [ "${nextRelease.version}" != "" ]; then ::set-output name=new_release_version::${nextRelease.version};fi'
  - - "@semantic-release/github"
    - assets:
        - path: ./target/clamapi*.jar
          label: Clamapi Jar

