name: Build
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build & Push docker image
        id: build_docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{github.repository}}
          push: true
          tag_with_ref: true
          add_git_labels: true
