name: maven-release

on:
  push:
    branches: [ master ]

jobs:
  maven-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Setup maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Semantic Release
        id: semantic-dry-run
        uses: cycjimmy/semantic-release-action@v2
        with:
          dry_run: true
          extra_plugins: conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upgrade pom version
        if: ${{ steps.semantic-dry-run.outputs.new_release_published }}
        run: mvn versions:set -DnewVersion=${{ steps.semantic-dry-run.outputs.new_release_version }}

      - name: Maven Package
        run: mvn -B package

      - name: Code coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true

      - name: Push jib image
        if: ${{ steps.semantic-dry-run.outputs.new_release_published }}
        run: mvn -B com.google.cloud.tools:jib-maven-plugin:2.2.0:build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





